# Generated by Django 3.0.7 on 2021-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210327_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='currency',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
